latest C# quickstart for Docs
Azure-Samples/cognitive-services-speech-sdk pull request #1462
Opened 2022-04-11 23:34 UTC by eric-urban

## Purpose
Request to add the latest C# STT quickstart. Then we can import to Docs via the <stt-quickstart> tag.
* ...

## Pull Request Type
Sample is created via dotnet CLI without a VS solution.

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x ] Documentation content changes
[ ] Other... Please describe:
```

2022-04-11 23:39 UTC, eric-urban commented
@dargilco @trrwilson please check

2022-04-12 16:49 UTC, dargilco requested changes

2022-04-12 16:49 UTC, dargilco commented on quickstart/csharp/dotnetcore/from-microphone/README.md
> +For instructions on how to create and run this console application using the Speech SDK, see the [Speech to text quickstart](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/g
Remove "en-us" from the link

2022-04-12 16:49 UTC, dargilco commented on quickstart/csharp/dotnetcore/from-microphone/helloworld.sln
> -
Please don't delete the .sln file. Carbon automaticly builds the samples using the VS solution file in our CI/CD pipeline. And I think we want users to have VS solutions for all Windows samples, even if you can build on the command line. So we need to find a way to document both options (VS build or command line build). So maybe leave the VS and updat the README.md file to mention both options.

2022-04-12 16:49 UTC, dargilco commented on quickstart/csharp/dotnetcore/from-microphone/helloworld/Program.cs
> +// <stt-quickstart>
I was thinking maybe all our tags should start with a common prefix such as "code-embedded-in-microsoft-docs-..." or something of the sort, so both we (Carbon devs) and external developers know what these are for. Maybe discussed in the next meeting (but I'm out on Monday). Don't let that block this check in, just something to discuss. I think that would be helpful.

2022-04-12 16:49 UTC, dargilco commented on quickstart/csharp/dotnetcore/from-microphone/helloworld/Program.cs
> -            var config = SpeechConfig.FromSubscription("YourSubscriptionKey", "YourServiceRegion");
Please bring back the comments. We did not agree on deleting comments from GitHub quickstarts. If/when we have two versions of quickstarts, one solely dedicated to oneline-docs, we can remove comments from that version. But as long as we only have one version, we need comments in it.

2025-05-03 23:14 UTC, closed without merging