Add private endpoint and personal voice speaker profile ID.
Azure-Samples/cognitive-services-speech-sdk pull request #2293
Opened 2024-03-08 09:28 UTC by v-wangtong

## Purpose

* ...

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

2024-03-11 02:08 UTC, v-wangtong commented
I have read and agree to the Contributor License Agreement. @microsoft-github-policy-service agree company="Shanghai Wicresoft Co Ltd".


________________________________
From: microsoft-github-policy-service[bot] ***@***.***>
Sent: Friday, March 8, 2024 5:29 PM
To: Azure-Samples/cognitive-services-speech-sdk ***@***.***>
Cc: Tong Wang (Shanghai Wicresoft Co Ltd) ***@***.***>; Mention ***@***.***>
Subject: Re: [Azure-Samples/cognitive-services-speech-sdk] Add private endpoint and personal voice speaker profile ID. (PR #2293)


@v-wangtong<https://github.com/v-wangtong> please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.

@microsoft-github-policy-service agree [company="{your company}"]


Options:

  *   (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.

@microsoft-github-policy-service agree


  *   (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.

@microsoft-github-policy-service agree company="Microsoft"


Contributor License Agreement
Contribution License Agreement

This Contribution License Agreement (“Agreement”) is agreed to by the party signing below (“You”),
and conveys certain license rights to Microsoft Corporation and its affiliates (“Microsoft”) for Your
contributions to Microsoft open source projects. This Agreement is effective as of the latest signature
date below.

  1.  Definitions.
“Code” means the computer software code, whether in human-readable or machine-executable form,
that is delivered by You to Microsoft under this Agreement.
“Project” means any of the projects owned or managed by Microsoft and offered under a license
approved by the Open Source Initiative (www.opensource.org<http://www.opensource.org/>).
“Submit” is the act of uploading, submitting, transmitting, or distributing code or other content to any
Project, including but not limited to communication on electronic mailing lists, source code control
systems, and issue tracking systems that are managed by, or on behalf of, the Project for the purpose of
discussing and improving that Project, but excluding communication that is conspicuously marked or
otherwise designated in writing by You as “Not a Submission.”
“Submission” means the Code and any other copyrightable material Submitted by You, including any
associated comments and documentation.
  2.  Your Submission. You must agree to the terms of this Agreement before making a Submission to any
Project. This Agreement covers any and all Submissions that You, now or in the future (except as
described in Section 4 below), Submit to any Project.
  3.  Originality of Work. You represent that each of Your Submissions is entirely Your original work.
Should You wish to Submit materials that are not Your original work, You may Submit them separately
to the Project if You (a) retain all copyright and license information that was in the materials as You
received them, (b) in the description accompanying Your Submission, include the phrase “Submission
containing materials of a third party:” followed by the names of the third party and any licenses or other
restrictions of which You are aware, and (c) follow any other instructions in the Project’s written
guidelines concerning Submissions.
  4.  Your Employer. References to “employer” in this Agreement include Your employer or anyone else
for whom You are acting in making Your Submission, e.g. as a contractor, vendor, or agent. If Your
Submission is made in the course of Your work for an employer or Your employer has intellectual
property rights in Your Submission by contract or applicable law, You must secure permission from Your
employer to make the Submission before signing this Agreement. In that case, the term “You” in this
Agreement will refer to You and the employer collectively. If You change employers in the future and
desire to Submit additional Submissions for the new employer, then You agree to sign a new Agreement
and secure permission from the new employer before Submitting those Submissions.
  5.  Licenses.

  *   Copyright License. You grant Microsoft, and those who receive the Submission directly or
indirectly from Microsoft, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license in the
Submission to reproduce, prepare derivative works of, publicly display, publicly perform, and distribute
the Submission and such derivative works, and to sublicense any or all of the foregoing rights to third
parties.
  *   Patent License. You grant Microsoft, and those who receive the Submission directly or
indirectly from Microsoft, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license under
Your patent claims that are necessarily infringed by the Submission or the combination of the
Submission with the Project to which it was Submitted to make, have made, use, offer to sell, sell and
import or otherwise dispose of the Submission alone or with the Project.
  *   Other Rights Reserved. Each party reserves all rights not expressly granted in this Agreement.
No additional licenses or rights whatsoever (including, without limitation, any implied licenses) are
granted by implication, exhaustion, estoppel or otherwise.

  1.  Representations and Warranties. You represent that You are legally entitled to grant the above
licenses. You represent that each of Your Submissions is entirely Your original work (except as You may
have disclosed under Section 3). You represent that You have secured permission from Your employer to
make the Submission in cases where Your Submission is made in the course of Your work for Your
employer or Your employer has intellectual property rights in Your Submission by contract or applicable
law. If You are signing this Agreement on behalf of Your employer, You represent and warrant that You
have the necessary authority to bind the listed employer to the obligations contained in this Agreement.
You are not expected to provide support for Your Submission, unless You choose to do so. UNLESS
REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, AND EXCEPT FOR THE WARRANTIES
EXPRESSLY STATED IN SECTIONS 3, 4, AND 6, THE SUBMISSION PROVIDED UNDER THIS AGREEMENT IS
PROVIDED WITHOUT WARRANTY OF ANY KIND, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY OF
NONINFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
  2.  Notice to Microsoft. You agree to notify Microsoft in writing of any facts or circumstances of which
You later become aware that would make Your representations in this Agreement inaccurate in any
respect.
  3.  Information about Submissions. You agree that contributions to Projects and information about
contributions may be maintained indefinitely and disclosed publicly, including Your name and other
information that You submit with Your Submission.
  4.  Governing Law/Jurisdiction. This Agreement is governed by the laws of the State of Washington, and
the parties consent to exclusive jurisdiction and venue in the federal courts sitting in King County,
Washington, unless no federal subject matter jurisdiction exists, in which case the parties consent to
exclusive jurisdiction and venue in the Superior Court of King County, Washington. The parties waive all
defenses of lack of personal jurisdiction and forum non-conveniens.
  5.  Entire Agreement/Assignment. This Agreement is the entire agreement between the parties, and
supersedes any and all prior agreements, understandings or communications, written or oral, between
the parties relating to the subject matter hereof. This Agreement may be assig [...]

2024-03-11 02:15 UTC, v-wangtong commented
@microsoft-github-policy-service agree company="Microsoft".

________________________________
From: microsoft-github-policy-service[bot] ***@***.***>
Sent: Monday, March 11, 2024 10:08 AM
To: Azure-Samples/cognitive-services-speech-sdk ***@***.***>
Cc: Tong Wang (Shanghai Wicresoft Co Ltd) ***@***.***>; Mention ***@***.***>
Subject: Re: [Azure-Samples/cognitive-services-speech-sdk] Add private endpoint and personal voice speaker profile ID. (PR #2293)


@v-wangtong<https://github.com/v-wangtong> the command you issued was incorrect. Please try again.

Examples are:

@microsoft-github-policy-service agree


and

@microsoft-github-policy-service agree company="your company"


—
Reply to this email directly, view it on GitHub<https://github.com/Azure-Samples/cognitive-services-speech-sdk/pull/2293#issuecomment-1987503614>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BGYDC4MCW6MU6DYDLB7F4CTYXUG3LAVCNFSM6AAAAABEMP2YT2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSOBXGUYDGNRRGQ>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-03-13 02:18 UTC, yinhew requested changes

2024-03-13 03:41 UTC, yinhew commented on samples/js/browser/avatar/README.md
> +        * Private EndPoint - the private endpoint of your Azure speech resource. The format should be like: https://{your custom name}.cognitiveservices.azure.com.
Can you add `` to the url?

2024-03-13 03:41 UTC, yinhew commented on samples/js/browser/avatar/README.md
> +        * Private EndPoint - the private endpoint of your Azure speech resource. The format should be like: https://{your custom name}.cognitiveservices.azure.com.
Can you add `` to the url?

2024-03-13 03:52 UTC, yinhew commented on samples/js/browser/avatar/js/basic.js
>      speechSynthesisConfig.endpointId = document.getElementById('customVoiceEndpointId').value
Can you put indent here? for better readability?

2024-03-13 03:53 UTC, yinhew commented on samples/js/browser/avatar/js/chat.js
>      speechSynthesisConfig.endpointId = document.getElementById('customVoiceEndpointId').value
Can you put indent here? for better readability?

2024-03-13 04:20 UTC, yinhew commented on samples/js/browser/avatar/js/basic.js
>      speechSynthesisConfig.speechSynthesisVoiceName = document.getElementById('ttsVoice').value
Please remove this line. It can trigger bug when personal version is set.

2024-03-13 04:21 UTC, yinhew commented on samples/js/browser/avatar/js/chat.js
>      speechSynthesisConfig.endpointId = document.getElementById('customVoiceEndpointId').value
Please remove this line. It can trigger bug when personal version is set.

2024-03-13 04:21 UTC, yinhew commented on samples/js/browser/avatar/js/chat.js
> +   :SpeechSDK.SpeechConfig.fromSubscription(cogSvcSubKey, cogSvcRegion)
Can you put indent here? for better readability?

2024-03-13 04:22 UTC, yinhew commented on samples/js/browser/avatar/js/basic.js
> +    :SpeechSDK.SpeechConfig.fromSubscription(cogSvcSubKey, cogSvcRegion)
Can you put indent for these 2 lines? for better readability.

2024-03-13 05:45 UTC, yinhew commented on samples/js/browser/avatar/js/basic.js
> +    const privateEndpointCheckBox = document.getElementById('enablePrivateEndpoint').checked
privateEndpointCheckBox => privateEndpointEnabled

2024-03-13 05:47 UTC, yinhew commented on samples/js/browser/avatar/js/basic.js
> +    if( privateEndpointCheckBox && privateEndpoint === ''){
Regarding to space, please keep consistent coding style with existing code, this line should be like below:

if (privateEndpointCheckBox && privateEndpoint === '') {

2024-03-13 05:47 UTC, yinhew commented on samples/js/browser/avatar/js/basic.js
> +    if(privateEndpointCheckBox){
Regarding to space, please keep consistent coding style with existing code, this line should be like below:

if (privateEndpointCheckBox) {

2024-03-13 05:48 UTC, yinhew commented on samples/js/browser/avatar/js/basic.js
> +    }else {
Regarding to space, please keep consistent coding style with existing code, this line should be like below:

    } else {

2024-03-13 05:49 UTC, yinhew commented on samples/js/browser/avatar/js/basic.js
> +window.updatePrivateEndpoint = () =>{
space:

window.updatePrivateEndpoint = () => {

2024-03-13 05:49 UTC, yinhew commented on samples/js/browser/avatar/js/basic.js
> +    if(document.getElementById('enablePrivateEndpoint').checked) {
Space:

    if (document.getElementById('enablePrivateEndpoint').checked) {

2024-03-13 05:50 UTC, yinhew commented on samples/js/browser/avatar/js/chat.js
> +    if( privateEndpointCheckBox && privateEndpoint === ''){
Space:
    if (privateEndpointCheckBox && privateEndpoint === '') {

2024-03-13 05:50 UTC, yinhew commented on samples/js/browser/avatar/js/chat.js
> +    if(privateEndpointCheckBox){
Space:
    if (privateEndpointCheckBox) {

2024-03-13 05:51 UTC, yinhew commented on samples/js/browser/avatar/js/chat.js
> +    }else {
Space:

    } else {

2024-03-13 05:51 UTC, yinhew commented on samples/js/browser/avatar/js/chat.js
> +window.updatePrivateEndpoint = () =>{
space

2024-03-13 05:51 UTC, yinhew commented on samples/js/browser/avatar/js/chat.js
> +    if(document.getElementById('enablePrivateEndpoint').checked) {
space

2024-03-13 05:51 UTC, yinhew commented on samples/js/browser/avatar/js/chat.js
> +    }else{
space

2024-03-13 05:52 UTC, yinhew commented on samples/js/browser/avatar/js/chat.js
> +    const privateEndpointCheckBox = document.getElementById('enablePrivateEndpoint').checked
privateEndpointCheckBox => privateEndpointEnabled

2024-03-13 05:59 UTC, yinhew commented on samples/js/browser/avatar/js/basic.js
>      speechSynthesisConfig.speechSynthesisVoiceName = document.getElementById('ttsVoice').value
Looks you still didn't remove this line

2024-03-13 06:00 UTC, yinhew commented on samples/js/browser/avatar/js/chat.js
>      speechSynthesisConfig.speechSynthesisVoiceName = document.getElementById('ttsVoice').value
Please remove this line. It can trigger bug when personal version is set.

2024-03-13 06:02 UTC, yinhew commented on samples/js/browser/avatar/js/chat.js
> +    if(document.getElementById('enablePrivateEndpoint').checked) {
Space after "if"

2024-03-13 06:03 UTC, yinhew commented on samples/js/browser/avatar/js/chat.js
> +    if(privateEndpointEnabled) {
Space after "if"

2024-03-13 06:28 UTC, yinhew commented on samples/js/browser/avatar/README.md
> +        * Enable Private Endpoint - check this if you want to apply private endpoint. If you check this, you need to fill Private Endpoint section below. Please refer to [speech-services-private-link
Remove en-us from the link URL

2024-03-13 06:28 UTC, yinhew commented on samples/js/browser/avatar/README.md
> +        * Personal Voice Speaker Profile ID - the personal voice speaker profile ID of your personal voice. Please follow [here](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/per
Remove en-us from the link URL

2024-03-13 06:28 UTC, yinhew commented on samples/js/browser/avatar/README.md
> +        *  Enable Private Endpoint - check this if you want to apply private endpoint. If you check this, you need to fill Private Endpoint section below. Please refer to [speech-services-private-lin
Remove en-us from the link URL

2024-03-13 06:29 UTC, yinhew commented on samples/js/browser/avatar/README.md
> +        * Personal Voice Speaker Profile ID - the personal voice speaker profile ID of your personal voice. Please follow [here](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/per
Remove en-us from the link URL

2024-03-13 07:08 UTC, yinhew approved these changes

2024-03-13 13:13 UTC, yinhew commented
./azp run

2024-03-13 13:14 UTC, yinhew reviewed
/azp run

2024-03-13 13:36 UTC, yulin-li commented
/azp run

2024-03-13 14:44 UTC, merged